### PR TITLE
Inner loop fix

### PR DESCRIPTION
**Pull request by yanefingon**
This is essentially the most important fix as it directly addresses the bug and proposes a working (I hope) solution to it by rewriting the inner loop logic.
```rust
{
    let m = (l + r) / 2;
    if self[m] == i 
    {
        Some(m)
    }
    else 
    {
        if l != r
        {
            if self[m] > i
            {
                self.remove(m);
                // a special care is only needed for the left edge 
                // since "r" always is always bigger than "m" at least by 1
                if m == l { self.stalin(i, l, m) } 
                else { self.stalin(i, l, m - 1) }
            } 
            else 
            {
                self.remove(m);
                self.stalin(i, m, r - 1)
            }
        }
        else { None }
    }
}
```

### CODE REVIEW

**Comment by yanefingon** [comment]
As far as I can see @Miezhiko, you've decided to keep your original inner loop structure. But just so that you know: the "check for fallthrough" makes the bug a bit less harmful but it is still in there.
And of the main issue with it is that it corrupts the "binarity" that lies at the heart of the algorithm. 
This leads to a highly unstable performance and "binary" advantage loss even for fully sorted inputs, especially with the rise of the number of elements in an array.   
Each step to the right you take, the more you ruin the "binary equilibrium" by the measure of 1 within the vector.
 
 ---
image
current inner cycle

---
image
a proposed inner cycle

---
These are just artificial examples but the bigger the array is the more frequent this difference is gonna be between the theoretical logarithmical running time for a ***true binary*** division and the real division of your inner loop influenced by the boundaries' shift and overcrossing.

**Comment by Miezhiko** [comment]
@yanefingon may you reproduce the bug, so I will know where else it may leak out =_= this performance example is not looking meaningful for me at all... I don't think that on bigger arrays shift to one element will be harmful, more like the bigger array the more harmful is this shift, sure dropping element with recreating array on each step is extremely slow operation however we don't think about it here ^_^

**Comment by yanefingon** [comment]
@Miezhiko this was not a *performance* example but rather one to illustrate the equilibrium of 2 parts of any division at each step being compromised. The principle all binary algorithms are driven by is the invariant of length correspondence of both parts at any given point. This leads to the logarithmic time. The problem here is with the second part:
image
  
This element is under further investigation whatever the test on it is. 
One might solve an issue as follows:
image

e.g.

**Comment by Miezhiko** [comment]
@yanefingon more likely there should be `m - 2` in first, what do you think?

**Comment by Miezhiko** [comment]
@yanefingon I guess this is fixed here https://github.com/Miezhiko/stalin-binary-search/commit/04162f6e8500ae96e4d30ae9e769eea921645f7e

**Comment by yanefingon** [comment]
now it's better

**Pull request merged**
