### PR TITLE
Overcrossing pointers vulnerability

### PR DESCRIPTION
**Pull request by yanefingon**
This one adds an overview of a pointer-overcrossing bug and brings an in-depth explanation of the problem as well as its roots. 
image

### CODE REVIEW

**Comment by yanefingon** [comment]
@Miezhiko this one was never resolved but rather closed which I'd like to consider a missclick leaving the dangling link in the main part of the documentation [here](../blob/mawa/docs/complexity_analysis.md)
Renders the [document](https://github.com/yanefingon/stalin-binary-search/blob/overcrossing_pointers_vulnerability/docs/overcrossing_pointers_vulnerability.md) at the heart of this PR unreachable.
image
image
image

**Comment by Miezhiko** [comment]
@yanefingon may you rebase this branch on top of merged one?

**Comment by Miezhiko** [comment]
nevermind, cherry-picked missing commits

**Comment by yanefingon** [comment]
> @yanefingon may you rebase this branch on top of merged one?

@Miezhiko then it doesn't count up to your 4 hacktober things, does it?

**Comment by Miezhiko** [comment]
@yanefingon it doesn't count in any case unless there is some hackember fest ^_^

**Comment by yanefingon** [comment]
@Miezhiko well, it still does as the original PR was pushed prior to 11.01. All it takes is to:
- merge it, ***or***
- give it an approving review, ***or***
- add a **hacktoberfest-accepted** label to it

**Comment by Miezhiko** [comment]
@yanefingon I still doubt, it already depends on time zone and after I've got no requested t-shirt from the previous year, it was tracking until it hit mail of my country and I guess it was just lost or stolen there.

**Comment by yanefingon** [comment]
@Miezhiko missed once again 😬 . That PR was already accepted. Try adding a label to ***this*** topic
image

**Comment by yanefingon** [comment]
@Miezhiko we were just a mere single wee mistake away. These 3 got through
image
This one did not make it. All due to the merge second, 8-22pm gmt-12 which was meant to be prior to the deadline.
image
Still, pretty nice job. But looks like those tiny details matter more than you think of them, as they always do.

**Pull request closed without merging**
